//OLED settings
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP27
#define I2C1_SCL_PIN GP28

//RGB
#define WS2812_DI_PIN GP26
#define RGBLIGHT_LED_COUNT 101

#define RGBLIGHT_MODE_RAINBOW_MOOD
#define RGBLIGHT_MODE_RGB_TEST
#define RGBLIGHT_MODE_TWINKLE
#define RGBLIGHT_LIMIT_VAL 100

#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_MOOD


//encoders
#define ENCODER_A_PINS { GP21, GP22 }
